# Generated by Django 5.2.7 on 2025-10-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faction', models.CharField(max_length=100)),
                ('skin', models.CharField(max_length=100)),
                ('camo', models.CharField(max_length=100)),
                ('unlock', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='game/')),
            ],
        ),
    ]
