# Generated by Django 5.2.7 on 2025-10-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='game/'),
        ),
    ]
